### ISSUE TITLE
Either.of when inside of another map loses it's "this"

### ISSUE THREAD

**Issue by tb01923** [folktale/data.either#9]
I am new to the functional approach, and am playing along with mostly-adequate-guide and the IO type.  I want to resolve IO to an Either error array. While this may not be the right approach, but the "this" inside of the Either.of is that of the someIO instance.   The code looks like:

    someIO.map(Either.of) 

However 

   someIO.map(Maybe.of)

Works fine.  I think the change is as simple as From

Either.of = function(a) {
  return this.Right(a)
}

To

Either.of = function(a) {
  return Either.prototype.Right(a)
}

which would be consistent with the code in data.maybe

**Comment by robotlolita** [comment]
Hmm, this is (technically) a problem with the `Maybe` library. But I guess I'll just end up changing everything to refer to the objects statically, since it's unlikely that people will inherit from Data.Maybe anyway.

I should review all libraries later this week.

**Comment by tb01923** [comment]
@robotlolita could you help fill in my knowedge gap?   Why is the problem technically with the Maybe library?  Is the logic:

const either = something.map(Either.of)

not proper or idiomatic of functional programming?

**Comment by robotlolita** [comment]
@tb01923 In parts because the Data.* libraries were originally designed following a prototype-OO design, so they accounted for people who could want to inherit from these libraries and provide a different of functionality. But mostly because of this: https://github.com/folktale/data.validation/issues/10#issuecomment-194803291

Moving forward, I'm making all methods that don't need to use the instance's data a static function, so this is fixed in 1.4.0
